baseurl = "http://xiaoxiyao.ml"
languageCode = "zh-cn"
title = "xiaoxiyao's blog"
theme = "material-lite"
Paginate = 5

[[menu.main]]
    name = "学无止境"
    pre = "<i class='material-icons'>edit</i>"
    url = "/categories/学无止境"
[[menu.main]]
    name = "杂七杂八"
    pre = "<i class='material-icons'>view_quilt</i>"
    url = "/categories/杂七杂八"
[[menu.main]]
    name = "资源分享"
    pre = "<i class='material-icons'>card_giftcard</i>"
    url = "/categories/资源分享"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
#  TwitterUser = "SamuelDebruyn"
#  FacebookUser = "facebook"
  GooglePlusUser = "103579200356573263980"
  GitHubUser = "xiaoxiyao"
  copyright = "&copy; xiaoxiyao 2015"
  author = "xiaoxiyao"
  description = "a blog build by hugo and material-design-lite on github pages(技术交流,分享一些个人经验与感悟)"
  keywords = "个人博客,技术交流,github pages,blog,material design,xiaoxiyao,分享,收藏,hugo"
#  background = "http://i3.piimg.com/da829ff5ad525994.jpg"
  logo = "http://i3.piimg.com/6a9b7cbe4962c6a5.png"
  DuoShuoName = "xiaoxiyao"
