baseurl = "http://xiaoxiyao.ml"
languageCode = "zh-cn"
title = "Blog 测试中"
theme = "material-lite"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
#  TwitterUser = "SamuelDebruyn"
#  FacebookUser = "facebook"
  GooglePlusUser = "XiaoLuo"
  GitHubUser = "xiaoxiyao"
  copyright = "&copy; Xiao XiYao 2015"
  author = "xiaoxiyao"
  description = "a blog build by hugo and material-design-lite on github pages"
  background = "http://i13.tietuku.com/da829ff5ad525994.jpg"
  logo = "http://i13.tietuku.com/6a9b7cbe4962c6a5.png"
  DuoShuoName = "xiaoxiyao"
