baseurl = "http://xiaoxiyao.github.io/blog"
languageCode = "zh-cn"
title = "Blog 测试中"
theme = "material-lite"

[params]
#  TwitterUser = "SamuelDebruyn"
#  FacebookUser = "facebook"
  GooglePlusUser = "XiaoLuo"
  GitHubUser = "xiaoxiyao"
  copyright = "&copy; Xiao XiYao 2015"
  author = "XiYao"
  description = "a blog build by hugo and material-design-lite on github pages"
  background = "http://i13.tietuku.com/95978b9e1290170a.jpg"
