baseurl = "http://xiaoxiyao.ml"
languageCode = "zh-cn"
title = "Blog 测试中"
theme = "material-lite"
Paginate = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
#  TwitterUser = "SamuelDebruyn"
#  FacebookUser = "facebook"
  GooglePlusUser = "XiaoLuo"
  GitHubUser = "xiaoxiyao"
  copyright = "&copy; xiaoxiyao 2015"
  author = "xiaoxiyao"
  description = "a blog build by hugo and material-design-lite on github pages(技术交流,分享一些个人经验与感悟)"
  keywords = "个人博客,技术交流,github pages,blog,material design,xiaoxiyao,分享,收藏,hugo"
  background = "http://i13.tietuku.com/da829ff5ad525994.jpg"
  logo = "http://i13.tietuku.com/6a9b7cbe4962c6a5.png"
  DuoShuoName = "xiaoxiyao"
