name = "Material"
description = "Material design theme for hugo blog"
license = "MIT"
tags = ["blog", "material design"]
min_version = 0.14

[author]
    name = "xiaoxiyao"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "xiaoxiyao"
    repo = "http://www.github.com/arnp/herring-cove"
